const UNIT_TRANSLATIONS: Record<string, string> = {
  // English to Arabic
  "kg": "كيلوغرام",
  "KG": "كيلوغرام",
  "Kg": "كيلوغرام",
  "kilogram": "كيلوغرام",
  "Kilogram": "كيلوغرام",
  "kg.": "كيلوغرام",
  "Liter": "لتر",
  "liter": "لتر",
  "L": "لتر",
  "l": "لتر",
  "lt": "لتر",
  "LT": "لتر",
  "unit": "وحدة",
  "Unit": "وحدة",
  "pcs": "قطعة",
  "PCS": "قطعة",
  "piece": "قطعة",
  "Piece": "قطعة",
  "box": "صندوق",
  "Box": "صندوق",
  "carton": "كرتونة",
  "Carton": "كرتونة",
  "ctn": "كرتونة",
  "CTN": "كرتونة",
  "package": "عبوة",
  "Package": "عبوة",
  "pack": "عبوة",
  "Pack": "عبوة",
  "pk": "عبوة",
  "PK": "عبوة",
  "case": "علبة",
  "Case": "علبة",
  "can": "علبة",
  "Can": "علبة",
  "bottle": "زجاجة",
  "Bottle": "زجاجة",
  "btl": "زجاجة",
  "BTL": "زجاجة",
  "bag": "كيس",
  "Bag": "كيس",
  "sack": "جوال",
  "Sack": "جوال",
  "dozen": "دزينة",
  "Dozen": "دزينة",
  "dz": "دزينة",
  "DZ": "دزينة",
  "meter": "متر",
  "Meter": "متر",
  "m": "متر",
  "M": "متر",
  "cm": "سم",
  "CM": "سم",
  "gram": "غرام",
  "Gram": "غرام",
  "g": "غرام",
  "G": "غرام",
  "ton": "طن",
  "Ton": "طن",
  "tonne": "طن",
  "Tonne": "طن",
  "roll": "لفافة",
  "Roll": "لفافة",
  "sheet": "ورقة",
  "Sheet": "ورقة",
  "pair": "زوج",
  "Pair": "زوج",
  "set": "مجموعة",
  "Set": "مجموعة",
  "tray": "صينية",
  "Tray": "صينية",
  "jar": "مرطبان",
  "Jar": "مرطبان",
  "bucket": "دلو",
  "Bucket": "دلو",
  "gallon": "جالون",
  "Gallon": "جالون",
  "gal": "جالون",
  "GAL": "جالون",
  "barrel": "برميل",
  "Barrel": "برميل",
  "bbl": "برميل",
  "BBL": "برميل",
  "crate": "قفص",
  "Crate": "قفص",
  "pallet": "منصة",
  "Pallet": "منصة",
};

export function translateUnit(unitName: string | null | undefined): string {
  if (!unitName) return "";
  const trimmed = unitName.trim();
  return UNIT_TRANSLATIONS[trimmed] || unitName;
}
